# Contain all data about model structure and training process.
# basically how to create the next instance of model.
model_type: window # step / window
model_params:
  n_steps_predict: 1 #How many future steps we predict?
  cols_predict: [ "respiration" ] #Null value means we are predicting all fields
  net_params:
    device: 'cuda:0'
    save_path: 'models'

    conv_layer_data:
      - channels: 32
        kernel_size: 3
        activation: relu

      - channels: 32
        kernel_size: 3
        activation: relu

      - channels: 32
        kernel_size: 3
        activation: relu

    lstm_hidden_size: 128,
    #Add learning rate and other session_payload for network
train:
  es_patience: 15
  epochs: 200
  sequence_limit: Null # No limit = Null
eval:
  es_patience: 7
  epochs: 200
  sequence_limit: Null # No limit = Null
  n_splits: 5
